-- 生产计划表
CREATE TABLE IF NOT EXISTS pro_plan (
    plan_id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '计划ID',
    plan_no VARCHAR(50) NOT NULL COMMENT '计划单号',
    plan_name VARCHAR(100) NOT NULL COMMENT '计划名称',
    plan_type VARCHAR(20) DEFAULT 'WEEK' COMMENT '计划类型: WEEK-周计划, MONTH-月计划, QUARTER-季度计划',
    start_date DATE COMMENT '计划开始日期',
    end_date DATE COMMENT '计划结束日期',
    status VARCHAR(20) DEFAULT 'DRAFT' COMMENT '计划状态: DRAFT-草稿, RELEASED-已发布, EXECUTING-执行中, COMPLETED-已完成, CANCELLED-已取消',
    schedule_type VARCHAR(20) DEFAULT 'SELF' COMMENT '排单类型: SELF-自身排单, ORDER-绑定销售订单',
    sales_order_id BIGINT COMMENT '销售订单ID',
    sales_order_no VARCHAR(50) COMMENT '销售订单号',
    customer_id BIGINT COMMENT '客户ID',
    customer_name VARCHAR(200) COMMENT '客户名称',
    item_id BIGINT NOT NULL COMMENT '产品ID',
    item_code VARCHAR(50) COMMENT '产品编码',
    item_name VARCHAR(200) COMMENT '产品名称',
    specification VARCHAR(500) COMMENT '规格型号',
    plan_qty DECIMAL(18,4) DEFAULT 0 COMMENT '计划产量',
    actual_qty DECIMAL(18,4) DEFAULT 0 COMMENT '实际产量',
    completion_rate DECIMAL(5,2) DEFAULT 0 COMMENT '完成率(%)',
    manager_id BIGINT COMMENT '负责人ID',
    manager_name VARCHAR(100) COMMENT '负责人姓名',
    remark VARCHAR(500) COMMENT '备注',
    create_by VARCHAR(64) COMMENT '创建者',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) COMMENT '更新者',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_plan_no (plan_no),
    KEY idx_status (status),
    KEY idx_item (item_id),
    KEY idx_date (start_date, end_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='生产计划表 - carels';
